# Generated by Django 4.0.6 on 2022-07-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False)),
                ('imagename', models.CharField(max_length=30)),
                ('imageurl', models.URLField()),
                ('imagedetails', models.TextField()),
            ],
        ),
    ]
